spring.application.name=Sentilytics

spring.datasource.url=jdbc:postgresql://localhost:5432/Sentilytics
spring.datasource.username=postgres
spring.datasource.password=1810
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


python.ml.api.url=http://localhost:8000/analyze